"""
Agent error handling, retry, criticality, timeouts, and fallbacks.
"""
from typing import Dict, Optional

# Criticality: critical = stop build; high = continue with fallback; low/medium = skip
AGENT_CRITICALITY: Dict[str, str] = {
    "Planner": "critical",
    "Requirements Clarifier": "high",
    "Stack Selector": "critical",
    "Native Config Agent": "medium",
    "Store Prep Agent": "low",
    "Frontend Generation": "high",
    "Backend Generation": "high",
    "Database Agent": "high",
    "API Integration": "medium",
    "Test Generation": "medium",
    "Image Generation": "low",
    "Video Generation": "low",
    "Security Checker": "medium",
    "Test Executor": "medium",
    "UX Auditor": "low",
    "Performance Analyzer": "low",
    "Deployment Agent": "medium",
    "Error Recovery": "low",
    "Memory Agent": "low",
    "PDF Export": "low",
    "Excel Export": "low",
    "Markdown Export": "low",
    "Scraping Agent": "low",
    "Automation Agent": "low",
    "Design Agent": "low",
    "Layout Agent": "low",
    "SEO Agent": "low",
    "Content Agent": "low",
    "Brand Agent": "low",
    "Documentation Agent": "low",
    "Validation Agent": "low",
    "Auth Setup Agent": "medium",
    "Payment Setup Agent": "medium",
    "Monitoring Agent": "low",
    "Accessibility Agent": "low",
    "DevOps Agent": "low",
    "Webhook Agent": "low",
    "Email Agent": "low",
    "Legal Compliance Agent": "low",
    "GraphQL Agent": "low",
    "WebSocket Agent": "low",
    "i18n Agent": "low",
    "Caching Agent": "low",
    "Rate Limit Agent": "low",
    "Search Agent": "low",
    "Analytics Agent": "low",
    "API Documentation Agent": "low",
    "Mobile Responsive Agent": "low",
    "Migration Agent": "low",
    "Backup Agent": "low",
    "Notification Agent": "low",
    "Design Iteration Agent": "low",
    "Code Review Agent": "low",
    "Staging Agent": "low",
    "A/B Test Agent": "low",
    "Feature Flag Agent": "low",
    "Error Boundary Agent": "low",
    "Logging Agent": "low",
    "Metrics Agent": "low",
    "Audit Trail Agent": "low",
    "Session Agent": "low",
    "OAuth Provider Agent": "low",
    "2FA Agent": "low",
    "Stripe Subscription Agent": "low",
    "Invoice Agent": "low",
    "CDN Agent": "low",
    "SSR Agent": "low",
    "Bundle Analyzer Agent": "low",
    "Lighthouse Agent": "low",
    "Schema Validation Agent": "low",
    "Mock API Agent": "low",
    "E2E Agent": "low",
    "Load Test Agent": "low",
    "Dependency Audit Agent": "low",
    "License Agent": "low",
    "Terms Agent": "low",
    "Privacy Policy Agent": "low",
    "Cookie Consent Agent": "low",
    "Multi-tenant Agent": "low",
    "RBAC Agent": "low",
    "SSO Agent": "low",
    "Audit Export Agent": "low",
    "Data Residency Agent": "low",
    "HIPAA Agent": "low",
    "SOC2 Agent": "low",
    "Penetration Test Agent": "low",
    "Incident Response Agent": "low",
    "SLA Agent": "low",
    "Cost Optimizer Agent": "low",
    "Accessibility WCAG Agent": "low",
    "RTL Agent": "low",
    "Dark Mode Agent": "low",
    "Keyboard Nav Agent": "low",
    "Screen Reader Agent": "low",
    "Component Library Agent": "low",
    "Design System Agent": "low",
    "Animation Agent": "low",
    "Chart Agent": "low",
    "Table Agent": "low",
    "Form Builder Agent": "low",
    "Workflow Agent": "low",
    "Queue Agent": "low",
}

# Timeout in seconds per agent (complex ones get more)
AGENT_TIMEOUTS: Dict[str, int] = {
    "Planner": 120,
    "Requirements Clarifier": 90,
    "Stack Selector": 60,
    "Native Config Agent": 90,
    "Store Prep Agent": 90,
    "Frontend Generation": 180,
    "Backend Generation": 180,
    "Database Agent": 90,
    "API Integration": 90,
    "Test Generation": 120,
    "Image Generation": 60,
    "Video Generation": 45,
    "Security Checker": 90,
    "Test Executor": 60,
    "UX Auditor": 60,
    "Performance Analyzer": 60,
    "Deployment Agent": 90,
    "Error Recovery": 60,
    "Memory Agent": 45,
    "PDF Export": 45,
    "Excel Export": 45,
    "Markdown Export": 45,
    "Scraping Agent": 90,
    "Automation Agent": 60,
    "Design Agent": 60,
    "Layout Agent": 90,
    "SEO Agent": 60,
    "Content Agent": 60,
    "Brand Agent": 45,
    "Documentation Agent": 90,
    "Validation Agent": 60,
    "Auth Setup Agent": 90,
    "Payment Setup Agent": 90,
    "Monitoring Agent": 60,
    "Accessibility Agent": 60,
    "DevOps Agent": 90,
    "Webhook Agent": 60,
    "Email Agent": 60,
    "Legal Compliance Agent": 60,
}

DEFAULT_TIMEOUT = 120


class AgentError(Exception):
    def __init__(self, agent_name: str, reason: str, severity: str = "high"):
        self.agent_name = agent_name
        self.reason = reason
        self.severity = severity
        super().__init__(f"{agent_name}: {reason}")


def get_criticality(agent_name: str) -> str:
    return AGENT_CRITICALITY.get(agent_name, "medium")


def get_timeout(agent_name: str) -> int:
    return AGENT_TIMEOUTS.get(agent_name, DEFAULT_TIMEOUT)


# User-facing error messages (for UI / logs)
AGENT_ERROR_MESSAGES: Dict[str, Dict[str, str]] = {
    "Planner": {
        "timeout": "Planning is taking longer than expected. Try a shorter description.",
        "empty_output": "Planning failed. Make sure your app description is clear and specific.",
    },
    "Stack Selector": {
        "timeout": "Tech stack selection timed out. Try again.",
        "empty_output": "Could not select stack. Refine your requirements.",
    },
    "Frontend Generation": {
        "timeout": "Frontend generation takes time for complex apps.",
        "empty_output": "Frontend generation failed. Using default template.",
    },
    "Backend Generation": {
        "timeout": "Backend generation is taking longer than usual.",
        "empty_output": "Backend generation failed. Using default template.",
    },
    "Security Checker": {
        "timeout": "Security hardening takes time for large apps.",
        "empty_output": "Security check found no improvements needed.",
    },
    "Performance Analyzer": {
        "timeout": "Performance analysis skipped (timeout).",
        "empty_output": "No optimization suggestions.",
    },
}


def get_error_message(agent_name: str, error_code: str) -> Optional[str]:
    """Return user-friendly message for agent failure."""
    msgs = AGENT_ERROR_MESSAGES.get(agent_name, {})
    return msgs.get(error_code) or msgs.get("empty_output") or f"Agent {agent_name} failed."


def generate_fallback(agent_name: str) -> str:
    """Minimal valid output when an agent fails."""
    fallbacks = {
        "Frontend Generation": "// Generated frontend (failed, using default React template)\nconst App = () => <div>Generated app placeholder</div>;\nexport default App;",
        "Backend Generation": "# Generated backend (failed, using default)\nfrom fastapi import FastAPI\napp = FastAPI()\n@app.get('/')\ndef root(): return {'message': 'Hello'}",
        "Database Agent": "-- Schema placeholder\n-- Tables: users, sessions",
        "Test Generation": "# Test generation failed, skipped",
        "Security Checker": "Security check skipped.",
        "Performance Analyzer": "Performance analysis skipped.",
        "Planner": "1. Implement core feature 2. Add tests 3. Deploy",
        "Stack Selector": "Frontend: React, Backend: FastAPI, DB: MongoDB",
        "Native Config Agent": '{"app.json":{"name":"App","slug":"app","version":"1.0.0","ios":{"bundleIdentifier":"com.example.app"},"android":{"package":"com.example.app"}}\n{"eas.json":{"build":{"preview":{"ios":{},"android":{}},"production":{"ios":{},"android":{}}}}}',
        "Store Prep Agent": "Store submission: see Expo EAS Submit docs for Apple and Google.",
        "Requirements Clarifier": "Clarifications skipped.",
        "Design Agent": '{"hero":{"position":"top-full","aspect":"16:9"},"feature_1":{"position":"grid","aspect":"1:1"},"feature_2":{"position":"grid","aspect":"1:1"}}',
        "Layout Agent": "// Layout merge skipped; use frontend as-is.",
        "SEO Agent": "Meta, OG, sitemap: standard setup.",
        "Content Agent": "Hero, features, CTA: use default copy.",
        "Brand Agent": '{"primary_color":"#1A1A1A","font_heading":"Inter"}',
        "Documentation Agent": "README: see deployment agent output.",
        "Validation Agent": "Validation rules: standard form checks.",
        "Auth Setup Agent": "Auth: JWT recommended; see docs.",
        "Payment Setup Agent": "Stripe: checkout + webhooks.",
        "Monitoring Agent": "Sentry + analytics recommended.",
        "Accessibility Agent": "a11y: ARIA, focus, contrast.",
        "DevOps Agent": "CI/CD: GitHub Actions; Dockerfile.",
        "Webhook Agent": "Webhook: verify signature, retries.",
        "Email Agent": "Transactional: Resend or SendGrid.",
        "Legal Compliance Agent": "GDPR: cookie banner, privacy link.",
        "GraphQL Agent": "GraphQL: schema + resolvers.",
        "WebSocket Agent": "WebSocket: real-time.",
        "i18n Agent": "i18n: locales, keys.",
        "Caching Agent": "Caching: Redis/edge.",
        "Rate Limit Agent": "Rate limit: quotas.",
        "Search Agent": "Search: Algolia/Meilisearch.",
        "Analytics Agent": "Analytics: GA4, events.",
        "API Documentation Agent": "API docs: OpenAPI.",
        "Mobile Responsive Agent": "Mobile: breakpoints.",
        "Migration Agent": "Migrations: DB scripts.",
        "Backup Agent": "Backup: strategy.",
        "Notification Agent": "Notifications: push, email.",
        "Design Iteration Agent": "Design iteration: feedback flow.",
        "Code Review Agent": "Code review: security, style.",
        "Staging Agent": "Staging: preview URLs.",
        "A/B Test Agent": "A/B: variant routing.",
        "Feature Flag Agent": "Feature flags.",
        "Error Boundary Agent": "Error boundaries.",
        "Logging Agent": "Logging: structured.",
        "Metrics Agent": "Metrics: Prometheus.",
        "Audit Trail Agent": "Audit: user actions.",
        "Session Agent": "Session: storage, expiry.",
        "OAuth Provider Agent": "OAuth: Google/GitHub.",
        "2FA Agent": "2FA: TOTP.",
        "Stripe Subscription Agent": "Stripe: plans.",
        "Invoice Agent": "Invoice: PDF.",
        "CDN Agent": "CDN: cache headers.",
        "SSR Agent": "SSR: Next.js.",
        "Bundle Analyzer Agent": "Bundle: code split.",
        "Lighthouse Agent": "Lighthouse: perf, a11y.",
        "Schema Validation Agent": "Schema: validation.",
        "Mock API Agent": "Mock: MSW.",
        "E2E Agent": "E2E: Playwright.",
        "Load Test Agent": "Load: k6.",
        "Dependency Audit Agent": "Deps: npm audit.",
        "License Agent": "License: OSS.",
        "Terms Agent": "Terms: ToS.",
        "Privacy Policy Agent": "Privacy: policy.",
        "Cookie Consent Agent": "Cookie: banner.",
        "Multi-tenant Agent": "Multi-tenant: isolation.",
        "RBAC Agent": "RBAC: roles.",
        "SSO Agent": "SSO: SAML.",
        "Audit Export Agent": "Audit export.",
        "Data Residency Agent": "Data residency.",
        "HIPAA Agent": "HIPAA: healthcare.",
        "SOC2 Agent": "SOC2: controls.",
        "Penetration Test Agent": "Pentest: checklist.",
        "Incident Response Agent": "Incident: runbook.",
        "SLA Agent": "SLA: uptime.",
        "Cost Optimizer Agent": "Cost: cloud.",
        "Accessibility WCAG Agent": "WCAG 2.1 AA.",
        "RTL Agent": "RTL: layout.",
        "Dark Mode Agent": "Dark mode: theme.",
        "Keyboard Nav Agent": "Keyboard: nav.",
        "Screen Reader Agent": "Screen reader.",
        "Component Library Agent": "Components: Shadcn.",
        "Design System Agent": "Design system: tokens.",
        "Animation Agent": "Animation: Framer.",
        "Chart Agent": "Charts: Recharts.",
        "Table Agent": "Tables: sort, pagination.",
        "Form Builder Agent": "Forms: dynamic.",
        "Workflow Agent": "Workflow: state machine.",
        "Queue Agent": "Queue: Bull/Celery.",
    }
    return fallbacks.get(agent_name, f"// {agent_name} generated no output (failed).")
